[package]
name = "emuworld"
version = "0.3.0"
description = "EmuWorld - All-in-one emulator launcher"
authors = ["EmuWorld Team"]
edition = "2021"

[lib]
name = "emuworld_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
zip = "2"
walkdir = "2"
dirs = "6"
sevenz-rust = "0.6"
urlencoding = "2.1.3"
base64 = "0.22"
tauri-plugin-deep-link = "2.4.7"
tauri-plugin-shell = "2.3.5"
tauri-plugin-single-instance = "2.4.0"
bytes = "1"
scraper = "0.26.0"
regex = "1"
chrono = { version = "0.4.44", features = ["clock"] }
discord-rich-presence = "1"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
gilrs = "0.11"
tauri-plugin-notification = "2"
