use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SetupFile {
    pub url: String,
    /// Relative path inside the emulator install dir (e.g. "keys.txt" or "portable/system/prod.keys")
    pub dest: String,
    /// If true, the downloaded file is a zip that should be extracted at `dest` (treated as dir)
    pub extract: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct EmulatorInfo {
    pub id: String,
    pub name: String,
    pub console: String,
    pub description: String,
    pub download_url: String,
    pub executable_name: String,
    pub supported_extensions: Vec<String>,
    pub icon: String,
    pub website: String,
    /// "zip" or "7z" — determines extraction method
    pub archive_type: String,
    pub category: String,
    /// Optional: libretro core filename (e.g., "mame_libretro.dll")
    pub core_name: Option<String>,
    /// Optional: extra files to download after install (keys, firmware, BIOS)
    #[serde(default)]
    pub setup_files: Vec<SetupFile>,
}

/// Returns the built-in catalog of supported emulators.
pub fn get_catalog() -> Vec<EmulatorInfo> {
    vec![
        // ═══════════════════════════════════════════════════════════
        //  NINTENDO
        // ═══════════════════════════════════════════════════════════
        EmulatorInfo {
            id: "mesen".to_string(),
            name: "Mesen 2".to_string(),
            console: "NES".to_string(),
            description: "Industry-leading accuracy for NES, SNES, and Game Boy. High-performance 64-bit emulator.".to_string(),
            download_url: "https://github.com/SourMesen/Mesen2/releases/download/2.1.1/Mesen_2.1.1_Windows.zip".to_string(),
            executable_name: "Mesen.exe".to_string(),
            supported_extensions: vec!["nes".to_string(), "fds".to_string(), "nsf".to_string()],
            icon: "🧬".to_string(),
            website: "https://www.mesen.ca/".to_string(),
            archive_type: "zip".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "mgba".to_string(),
            name: "mGBA".to_string(),
            console: "Game Boy Advance".to_string(),
            description: "A fast and accurate GBA emulator. Also supports Game Boy and Game Boy Color.".to_string(),
            download_url: "https://github.com/mgba-emu/mgba/releases/download/0.10.5/mGBA-0.10.5-win64.7z".to_string(),
            executable_name: "mGBA.exe".to_string(),
            supported_extensions: vec!["gba".to_string(), "gb".to_string(), "gbc".to_string()],
            icon: "🟢".to_string(),
            website: "https://mgba.io".to_string(),
            archive_type: "7z".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "snes9x".to_string(),
            name: "Snes9x".to_string(),
            console: "Super Nintendo".to_string(),
            description: "A portable, freeware Super Nintendo Entertainment System emulator.".to_string(),
            download_url: "https://github.com/snes9xgit/snes9x/releases/download/1.63/snes9x-1.63-win32-x64.zip".to_string(),
            executable_name: "snes9x-x64.exe".to_string(),
            supported_extensions: vec!["sfc".to_string(), "smc".to_string()],
            icon: "🟣".to_string(),
            website: "https://www.snes9x.com".to_string(),
            archive_type: "zip".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "project64".to_string(),
            name: "Project64".to_string(),
            console: "Nintendo 64".to_string(),
            description: "The leading N64 emulator with great compatibility and plugin support.".to_string(),
            download_url: "https://github.com/pj64team/Project64-Legacy/releases/download/Project64-1.6.4/Project64.Legacy.v1.6.4.The.End.-.2024.06.22.zip".to_string(),
            executable_name: "Project64.exe".to_string(),
            supported_extensions: vec!["z64".to_string(), "n64".to_string(), "v64".to_string()],
            icon: "🟡".to_string(),
            website: "https://www.pj64-emu.com".to_string(),
            archive_type: "zip".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "dolphin".to_string(),
            name: "Dolphin".to_string(),
            console: "GameCube / Wii".to_string(),
            description: "The gold standard emulator for GameCube and Wii games.".to_string(),
            download_url: "https://dl.dolphin-emu.org/releases/2412/dolphin-2412-x64.7z".to_string(),
            executable_name: "Dolphin.exe".to_string(),
            supported_extensions: vec!["iso".to_string(), "gcm".to_string(), "wbfs".to_string(), "rvz".to_string(), "ciso".to_string(), "gcz".to_string(), "nkit.iso".to_string()],
            icon: "🐬".to_string(),
            website: "https://dolphin-emu.org".to_string(),
            archive_type: "7z".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "melonds".to_string(),
            name: "melonDS".to_string(),
            console: "Nintendo DS".to_string(),
            description: "A modern Nintendo DS and DSi emulator focused on accuracy and performance.".to_string(),
            download_url: "https://github.com/melonDS-emu/melonDS/releases/download/1.1/melonDS-1.1-windows-x86_64.zip".to_string(),
            executable_name: "melonDS.exe".to_string(),
            supported_extensions: vec!["nds".to_string(), "ds".to_string()],
            icon: "📱".to_string(),
            website: "https://melonds.kuribo64.net".to_string(),
            archive_type: "zip".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "azahar".to_string(),
            name: "Azahar".to_string(),
            console: "Nintendo 3DS".to_string(),
            description: "Fork maintenu de Citra — émule la Nintendo 3DS avec bonne compatibilité et performances.".to_string(),
            download_url: "https://github.com/azahar-emu/azahar/releases/download/2125.1.2/azahar-windows-msvc-2125.1.2.zip".to_string(),
            executable_name: "azahar.exe".to_string(),
            supported_extensions: vec!["3ds".to_string(), "cci".to_string(), "cxi".to_string(), "app".to_string(), "3dsx".to_string(), "cia".to_string()],
            icon: "🌸".to_string(),
            website: "https://azahar-emu.org/".to_string(),
            archive_type: "zip".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "cemu".to_string(),
            name: "Cemu".to_string(),
            console: "Wii U".to_string(),
            description: "Highly polished Wii U emulator capable of running major titles at 4K and beyond.".to_string(),
            download_url: "https://github.com/cemu-project/Cemu/releases/download/v2.6/cemu-2.6-windows-x64.zip".to_string(),
            executable_name: "Cemu.exe".to_string(),
            supported_extensions: vec!["wud".to_string(), "wux".to_string(), "rpx".to_string()],
            icon: "📽️".to_string(),
            website: "https://cemu.info".to_string(),
            archive_type: "zip".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![
                SetupFile {
                    url: "https://gist.githubusercontent.com/MuTLY/7876de98811aac72b13b31c24c84b5be/raw/keys.txt".to_string(),
                    dest: "keys.txt".to_string(),
                    extract: false,
                },
            ],
        },
        EmulatorInfo {
            id: "ryubing".to_string(),
            name: "Ryubing".to_string(),
            console: "Nintendo Switch".to_string(),
            description: "A community fork of Ryujinx for Nintendo Switch emulation. Fast, accurate, and actively maintained on GitLab.".to_string(),
            download_url: "https://git.ryujinx.app/api/v4/projects/1/packages/generic/Ryubing/1.3.3/ryujinx-1.3.3-win_x64.zip".to_string(),
            executable_name: "Ryujinx.exe".to_string(),
            supported_extensions: vec!["nca".to_string(), "nro".to_string(), "nsp".to_string(), "xci".to_string()],
            icon: "🎮".to_string(),
            website: "https://git.ryujinx.app/ryubing/ryujinx".to_string(),
            archive_type: "zip".to_string(),
            category: "Nintendo".to_string(),
            core_name: None,
            setup_files: vec![
                SetupFile {
                    url: "https://raw.githubusercontent.com/THZoria/NX_Firmware/master/prod.keys".to_string(),
                    dest: "portable/system/prod.keys".to_string(),
                    extract: false,
                },
                SetupFile {
                    url: "https://github.com/THZoria/NX_Firmware/releases/download/22.1.0/Firmware.22.1.0.zip".to_string(),
                    dest: "portable/system/Contents/registered".to_string(),
                    extract: true,
                },
            ],
        },
        EmulatorInfo {
            id: "retroarch-vb".to_string(),
            name: "RetroArch (Virtual Boy)".to_string(),
            console: "Virtual Boy".to_string(),
            description: "Nintendo Virtual Boy via RetroArch's Beetle VB core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["vb".to_string(), "vboy".to_string()],
            icon: "🔴".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Nintendo".to_string(),
            core_name: Some("mednafen_vb_libretro.dll".to_string()),
            setup_files: vec![
                SetupFile {
                    url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/mednafen_vb_libretro.dll.zip".to_string(),
                    dest: "cores".to_string(),
                    extract: true,
                },
            ],
        },
        // ═══════════════════════════════════════════════════════════
        //  SONY
        // ═══════════════════════════════════════════════════════════
        EmulatorInfo {
            id: "duckstation".to_string(),
            name: "DuckStation".to_string(),
            console: "PlayStation 1".to_string(),
            description: "A PS1 emulator focused on playability, speed, and long-term maintainability.".to_string(),
            download_url: "https://github.com/stenzek/duckstation/releases/download/latest/duckstation-windows-x64-release.zip".to_string(),
            executable_name: "duckstation-qt-x64-ReleaseLTCG.exe".to_string(),
            supported_extensions: vec!["bin".to_string(), "iso".to_string(), "cue".to_string(), "chd".to_string()],
            icon: "⚪".to_string(),
            website: "https://www.duckstation.org".to_string(),
            archive_type: "zip".to_string(),
            category: "Sony".to_string(),
            core_name: None,
            setup_files: vec![
                SetupFile {
                    url: "https://ps1emulator.com/SCPH1001.BIN".to_string(),
                    dest: "bios/SCPH1001.BIN".to_string(),
                    extract: false,
                },
            ],
        },
        EmulatorInfo {
            id: "pcsx2".to_string(),
            name: "PCSX2".to_string(),
            console: "PlayStation 2".to_string(),
            description: "The most trusted PlayStation 2 emulator with Qt interface and Vulkan support.".to_string(),
            download_url: "https://github.com/PCSX2/pcsx2/releases/download/v2.6.3/pcsx2-v2.6.3-windows-x64-Qt.7z".to_string(),
            executable_name: "pcsx2-qt.exe".to_string(),
            supported_extensions: vec!["iso".to_string(), "bin".to_string(), "chd".to_string()],
            icon: "🔵".to_string(),
            website: "https://pcsx2.net".to_string(),
            archive_type: "7z".to_string(),
            category: "Sony".to_string(),
            core_name: None,
            setup_files: vec![
                SetupFile {
                    url: "https://archive.org/download/ps2-bios-megadump/PS2_BIOS.zip".to_string(),
                    dest: "bios".to_string(),
                    extract: true,
                },
            ],
        },
        EmulatorInfo {
            id: "rpcs3".to_string(),
            name: "RPCS3".to_string(),
            console: "PlayStation 3".to_string(),
            description: "The world's first open-source PlayStation 3 emulator and debugger.".to_string(),
            download_url: "https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-ffeb16fe1ec7a6a62ac317270dab20197b060ef9/rpcs3-v0.0.37-18146-ffeb16fe_win64_msvc.7z".to_string(),
            executable_name: "rpcs3.exe".to_string(),
            supported_extensions: vec!["pbp".to_string(), "iso".to_string(), "pkg".to_string()],
            icon: "💿".to_string(),
            website: "https://rpcs3.net".to_string(),
            archive_type: "7z".to_string(),
            category: "Sony".to_string(),
            core_name: None,
            setup_files: vec![
                SetupFile {
                    url: "http://dus01.ps3.update.playstation.net/update/ps3/image/us/2026_0318_a2b60b6ac1d2e49e230144345616927c/PS3UPDAT.PUP".to_string(),
                    dest: "PS3UPDAT.PUP".to_string(),
                    extract: false,
                },
            ],
        },
        EmulatorInfo {
            id: "ppsspp".to_string(),
            name: "PPSSPP".to_string(),
            console: "PlayStation Portable".to_string(),
            description: "The best PSP emulator, capable of running games at full HD and beyond.".to_string(),
            download_url: "https://github.com/hrydgard/ppsspp/releases/download/v1.20.3/PPSSPP-v1.20.3-Windows-x64.zip".to_string(),
            executable_name: "PPSSPPWindows64.exe".to_string(),
            supported_extensions: vec!["iso".to_string(), "cso".to_string(), "pbp".to_string()],
            icon: "⬛".to_string(),
            website: "https://www.ppsspp.org".to_string(),
            archive_type: "zip".to_string(),
            category: "Sony".to_string(),
            core_name: None,
            setup_files: vec![],
        },

        // ═══════════════════════════════════════════════════════════
        //  SEGA
        // ═══════════════════════════════════════════════════════════
        EmulatorInfo {
            id: "flycast".to_string(),
            name: "Flycast".to_string(),
            console: "Dreamcast".to_string(),
            description: "Multi-platform Dreamcast, Naomi, and Atomiswave emulator.".to_string(),
            download_url: "https://github.com/flyinghead/flycast/releases/download/v2.6/flycast-win64-2.6.zip".to_string(),
            executable_name: "flycast.exe".to_string(),
            supported_extensions: vec!["gdi".to_string(), "cdi".to_string(), "chd".to_string(), "cue".to_string()],
            icon: "🌀".to_string(),
            website: "https://github.com/flyinghead/flycast".to_string(),
            archive_type: "zip".to_string(),
            category: "Sega".to_string(),
            core_name: None,
            setup_files: vec![],
        },
        EmulatorInfo {
            id: "retroarch-md".to_string(),
            name: "RetroArch (Mega Drive)".to_string(),
            console: "Mega Drive".to_string(),
            description: "Sega Mega Drive / Genesis via RetroArch's Genesis Plus GX core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["gen".to_string(), "md".to_string(), "smd".to_string(), "bin".to_string()],
            icon: "🎮".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Sega".to_string(),
            core_name: Some("genesis_plus_gx_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/genesis_plus_gx_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-sms".to_string(),
            name: "RetroArch (Master System)".to_string(),
            console: "Master System".to_string(),
            description: "Sega Master System via RetroArch's Genesis Plus GX core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["sms".to_string(), "sg".to_string()],
            icon: "🎮".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Sega".to_string(),
            core_name: Some("genesis_plus_gx_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/genesis_plus_gx_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-gg".to_string(),
            name: "RetroArch (Game Gear)".to_string(),
            console: "Game Gear".to_string(),
            description: "Sega Game Gear via RetroArch's Genesis Plus GX core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["gg".to_string()],
            icon: "🎮".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Sega".to_string(),
            core_name: Some("genesis_plus_gx_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/genesis_plus_gx_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-segacd".to_string(),
            name: "RetroArch (Sega CD)".to_string(),
            console: "Sega CD".to_string(),
            description: "Sega CD / Mega CD via RetroArch's Genesis Plus GX core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["cue".to_string(), "chd".to_string(), "iso".to_string()],
            icon: "💿".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Sega".to_string(),
            core_name: Some("genesis_plus_gx_libretro.dll".to_string()),
            setup_files: vec![
                SetupFile {
                    url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/genesis_plus_gx_libretro.dll.zip".to_string(),
                    dest: "cores".to_string(),
                    extract: true,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/segacd/bios_CD_E.bin".to_string(),
                    dest: "system/bios_CD_E.bin".to_string(),
                    extract: false,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/segacd/bios_CD_U.bin".to_string(),
                    dest: "system/bios_CD_U.bin".to_string(),
                    extract: false,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/segacd/bios_CD_J.bin".to_string(),
                    dest: "system/bios_CD_J.bin".to_string(),
                    extract: false,
                },
            ],
        },
        EmulatorInfo {
            id: "retroarch-32x".to_string(),
            name: "RetroArch (32X)".to_string(),
            console: "Sega 32X".to_string(),
            description: "Sega 32X via RetroArch's PicoDrive core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["32x".to_string(), "bin".to_string()],
            icon: "🎯".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Sega".to_string(),
            core_name: Some("picodrive_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/picodrive_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-saturn".to_string(),
            name: "RetroArch (Saturn)".to_string(),
            console: "Saturn".to_string(),
            description: "Sega Saturn via RetroArch's Kronos core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["cue".to_string(), "iso".to_string(), "chd".to_string()],
            icon: "🪐".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Sega".to_string(),
            core_name: Some("kronos_libretro.dll".to_string()),
            setup_files: vec![
                SetupFile {
                    url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/kronos_libretro.dll.zip".to_string(),
                    dest: "cores".to_string(),
                    extract: true,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/saturn/sega_101.bin".to_string(),
                    dest: "system/sega_101.bin".to_string(),
                    extract: false,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/saturn/mpr-17933.bin".to_string(),
                    dest: "system/mpr-17933.bin".to_string(),
                    extract: false,
                },
            ],
        },

        // ═══════════════════════════════════════════════════════════
        //  MICROSOFT
        // ═══════════════════════════════════════════════════════════
        EmulatorInfo {
            id: "xemu".to_string(),
            name: "xemu".to_string(),
            console: "Xbox".to_string(),
            description: "Émulateur Xbox original open-source. Nécessite les jeux en format .iso (xiso).".to_string(),
            download_url: "https://github.com/xemu-project/xemu/releases/download/v0.8.135/xemu-win-x86_64-release.zip".to_string(),
            executable_name: "xemu.exe".to_string(),
            supported_extensions: vec!["iso".to_string(), "xbe".to_string()],
            icon: "❎".to_string(),
            website: "https://xemu.app".to_string(),
            archive_type: "zip".to_string(),
            category: "Microsoft".to_string(),
            core_name: None,
            setup_files: vec![
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/xbox/mcpx_1.0.bin".to_string(),
                    dest: "mcpx_1.0.bin".to_string(),
                    extract: false,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/xbox/Complex_4627v1.03.bin".to_string(),
                    dest: "Complex_4627v1.03.bin".to_string(),
                    extract: false,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/xbox/xbox_hdd.qcow2".to_string(),
                    dest: "xbox_hdd.qcow2".to_string(),
                    extract: false,
                },
            ],
        },

        EmulatorInfo {
            id: "xenia".to_string(),
            name: "Xenia Canary".to_string(),
            console: "Xbox 360".to_string(),
            description: "Émulateur Xbox 360 expérimental. Bonne compatibilité sur les titres populaires.".to_string(),
            download_url: "https://github.com/xenia-canary/xenia-canary/releases/download/29311dd/xenia_canary_windows.zip".to_string(),
            executable_name: "xenia_canary.exe".to_string(),
            supported_extensions: vec!["iso".to_string(), "xex".to_string(), "zar".to_string()],
            icon: "🟢".to_string(),
            website: "https://xenia.jp".to_string(),
            archive_type: "zip".to_string(),
            category: "Microsoft".to_string(),
            core_name: None,
            setup_files: vec![],
        },

        // ═══════════════════════════════════════════════════════════
        //  ARCADE & RETRO
        // ═══════════════════════════════════════════════════════════
        EmulatorInfo {
            id: "retroarch-arcade".to_string(),
            name: "RetroArch (Arcade MAME)".to_string(),
            console: "Arcade".to_string(),
            description: "Thousands of arcade classics via RetroArch's MAME core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["zip".to_string(), "7z".to_string()],
            icon: "🕹️".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("mame_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/mame_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-neogeo".to_string(),
            name: "RetroArch (Neo-Geo)".to_string(),
            console: "Neo-Geo".to_string(),
            description: "SNK Neo-Geo arcade and home console systems via RetroArch.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["zip".to_string(), "7z".to_string()],
            icon: "🅰️".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("fbneo_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/fbneo_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-pce".to_string(),
            name: "RetroArch (PC Engine)".to_string(),
            console: "PC Engine".to_string(),
            description: "PC Engine / TurboGrafx-16 classics via RetroArch.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["pce".to_string(), "cue".to_string()],
            icon: "🔶".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("mednafen_pce_fast_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/mednafen_pce_fast_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-atari2600".to_string(),
            name: "RetroArch (Atari 2600)".to_string(),
            console: "Atari 2600".to_string(),
            description: "Atari 2600 via RetroArch's Stella core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["a26".to_string(), "bin".to_string()],
            icon: "🟤".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("stella_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/stella_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-atari5200".to_string(),
            name: "RetroArch (Atari 5200)".to_string(),
            console: "Atari 5200".to_string(),
            description: "Atari 5200 via RetroArch's Atari800 core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["a52".to_string(), "bin".to_string(), "rom".to_string()],
            icon: "🕹️".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("atari800_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/atari800_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-atari7800".to_string(),
            name: "RetroArch (Atari 7800)".to_string(),
            console: "Atari 7800".to_string(),
            description: "Atari 7800 ProSystem via RetroArch.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["a78".to_string(), "bin".to_string()],
            icon: "🕹️".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("prosystem_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/prosystem_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-jaguar".to_string(),
            name: "RetroArch (Jaguar)".to_string(),
            console: "Jaguar".to_string(),
            description: "Atari Jaguar via RetroArch's Virtual Jaguar core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["j64".to_string(), "jag".to_string(), "rom".to_string(), "bin".to_string()],
            icon: "🐆".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("virtualjaguar_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/virtualjaguar_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-lynx".to_string(),
            name: "RetroArch (Lynx)".to_string(),
            console: "Lynx".to_string(),
            description: "Atari Lynx via RetroArch's Handy core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["lnx".to_string(), "lyx".to_string(), "o".to_string()],
            icon: "🎮".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("handy_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/handy_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-tg16".to_string(),
            name: "RetroArch (TurboGrafx-16)".to_string(),
            console: "TurboGrafx-16".to_string(),
            description: "TurboGrafx-16 / PC Engine via RetroArch's Mednafen PCE Fast core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["pce".to_string(), "sgx".to_string(), "cue".to_string(), "chd".to_string()],
            icon: "📺".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("mednafen_pce_fast_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/mednafen_pce_fast_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },
        EmulatorInfo {
            id: "retroarch-tgcd".to_string(),
            name: "RetroArch (TurboGrafx-CD)".to_string(),
            console: "TurboGrafx-CD".to_string(),
            description: "TurboGrafx-CD / PC Engine CD via RetroArch's Mednafen PCE Fast core.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["cue".to_string(), "chd".to_string(), "iso".to_string()],
            icon: "💿".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("mednafen_pce_fast_libretro.dll".to_string()),
            setup_files: vec![
                SetupFile {
                    url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/mednafen_pce_fast_libretro.dll.zip".to_string(),
                    dest: "cores".to_string(),
                    extract: true,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/tgcd/syscard3.pce".to_string(),
                    dest: "system/syscard3.pce".to_string(),
                    extract: false,
                },
            ],
        },
        EmulatorInfo {
            id: "retroarch-cdi".to_string(),
            name: "RetroArch (CD-i)".to_string(),
            console: "CD-i".to_string(),
            description: "Philips CD-i via SAME CDi (expérimental).".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["chd".to_string(), "iso".to_string(), "cue".to_string()],
            icon: "📀".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("same_cdi_libretro.dll".to_string()),
            setup_files: vec![
                SetupFile {
                    url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/same_cdi_libretro.dll.zip".to_string(),
                    dest: "cores".to_string(),
                    extract: true,
                },
                SetupFile {
                    url: "https://raw.githubusercontent.com/fj123u/EmuWorld/main/bios/cdi/cdimono1.zip".to_string(),
                    dest: "system/cdimono1.zip".to_string(),
                    extract: false,
                },
            ],
        },
        EmulatorInfo {
            id: "retroarch-wswan".to_string(),
            name: "RetroArch (WonderSwan)".to_string(),
            console: "WonderSwan".to_string(),
            description: "Bandai WonderSwan / WonderSwan Color via RetroArch.".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["ws".to_string(), "wsc".to_string()],
            icon: "🔲".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Arcade & Retro".to_string(),
            core_name: Some("mednafen_wswan_libretro.dll".to_string()),
            setup_files: vec![SetupFile {
                url: "https://buildbot.libretro.com/nightly/windows/x86_64/latest/mednafen_wswan_libretro.dll.zip".to_string(),
                dest: "cores".to_string(),
                extract: true,
            }],
        },

        // ═══════════════════════════════════════════════════════════
        //  MULTI-SYSTEM
        // ═══════════════════════════════════════════════════════════
        EmulatorInfo {
            id: "retroarch".to_string(),
            name: "RetroArch".to_string(),
            console: "Multi-System".to_string(),
            description: "The ultimate all-in-one frontend for emulators (cores).".to_string(),
            download_url: "https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z".to_string(),
            executable_name: "retroarch.exe".to_string(),
            supported_extensions: vec!["nes".to_string(), "sfc".to_string(), "gba".to_string(), "md".to_string()],
            icon: "🔄".to_string(),
            website: "https://www.retroarch.com".to_string(),
            archive_type: "7z".to_string(),
            category: "Multi-System".to_string(),
            core_name: None,
            setup_files: vec![],
        },
    ]
}
